<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    $vendorDir . '/kriswallsmith/assetic/src/functions.php',
    $vendorDir . '/oodle/krumo/class.krumo.php',
);
